uCrawnler/config/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import RedirectView
import views as v


urlpatterns = [
    url('^login/', v.login,  name='login'),
    url('^logout/', v.logout, name='logout'),
    url('^editar_dados_usuario/', v.editar_dados_usuario, name='editar_dados_usuario'),
    url('^novo_usuario/$', v.novo_usuario, name="novo_usuario"),
    url('^novo_usuario/cadastrar/', v.cadastrar_novo_usuario, name="cadastrar_novo_usuario"),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^uCrawnler/', include('uCrawnler.urls', namespace='uCrawnler')),
    url(r'^$', RedirectView.as_view(url="/uCrawnler", permanent=True)),
]

uCrawnler/uCrawnler/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url('^$', views.index, name='index'),
    url('^iniciar/$', views.iniciar, name='iniciar'),
    url('^processamento/$', views.processamento, name='processamento'),
    url('^processamento/download/$', views.download_corpora, name='download_corpora'),
    url('^processamento/parar/$', views.parar_processamento, name='parar_processamento'),
]

uCrawnler/uCrawnler/models.py
 #-*- coding: utf-8 -*-

from django.db import models

class Document(models.Model):
    docfile = models.FileField(upload_to='%Y/%m/%d')

uCrawnler/uCrawnler/forms.py
from django import forms


class WtCoGenForm(forms.Form):
    def __init__(self, data = None):
        super(WtCoGenForm, self).__init__(self, data)
        if data:
            self.ativar_ngram = bool(int(data.POST.get(u'checkbox_ativarngram', False)))
            self.ativar_entidades = bool(int(data.POST.get(u'checkbox_ativarentidades', False)))
            self.gerar_vocabulario = bool(int(data.POST.get(u'checkbox_vocabulario', False)))
            self.formato_saida_entidades = data.POST.get(u'formato_saida_entidades')
            self.qtd_palavras = (None if not data.POST.get(u'input_qtd_palavras') else int(data.POST.get(u'input_qtd_palavras')))
            self.numero_gram = int(data.POST.get(u'numero_gram', 0))
            self.abrangencia = data.POST.get(u'abrangencia')
            self.tipo_saida = data.POST.get(u'radio_forma_saida')
            self.palavras_chave = data.POST.get(u'text_palavras_chave', "").encode("utf-8").split(",")
            self.limpar_caracteres = bool(int(data.POST.get("checkbox_limparcaracteres", False)))
            self.eliminar_pontuacao = bool(int(data.POST.get("checkbox_eliminarpontuacao", False)))
            self.eliminar_stopwords = bool(int(data.POST.get("checkbox_eliminarstopwords", False)))
            self.calcular_perplexidade = bool(int(data.POST.get("check_calcular_perplexidade", False)))


            self.arquivo_conf_twitter = data.FILES.get(u'arquivo_dados_acesso_twitter')
            self.coleta_arquivo_file = data.FILES.get(u'coleta_select_file')
            self.arquivo_perplexidade = data.FILES.get(u'file_carregar_arquivo_perplexidade')
            self.arquivo_corpus_proprio = data.FILES.get(u'arquivo_corpus_proprio')
            self.palavras_chave = data.POST.get(u'text_palavras_chave', "").encode("utf-8").split(",")
            self.opcao_coleta_selecionada = data.POST.get(u'fonte_coleta')
            self.slc_dominios = data.POST.getlist(u"slc_dominios[]", [])
            self.create_dict_opcoes()


    def create_dict_opcoes(self):
        self.opcoes = {
            "ativar_ngram": self.ativar_ngram,
            "ativar_entidades": self.ativar_entidades,
            "gerar_vocabulario": self.gerar_vocabulario,
            "formato_saida_entidades": self.formato_saida_entidades,
            "qtd_palavras": self.qtd_palavras,
            "numero_gram": self.numero_gram,
            "abrangencia": self.abrangencia,
            "palavras_chave": self.palavras_chave,
            "limpar_caracteres": self.limpar_caracteres,
            "eliminar_pontuacao": self.eliminar_pontuacao,
            "eliminar_stopwords": self.eliminar_stopwords,
            "calcular_perplexidade": self.calcular_perplexidade,
            "tipo_saida": self.tipo_saida,
        }

    def is_valid(self):
        pass

uCrawnler/uCrawnler/views.py
# -*- coding: utf-8 -*-
import os
from rexec import FileWrapper
from django.contrib.auth.decorators import login_required
from tweepy.error import TweepError

from controler.crawler_control_base import CrawlerFacadeBase
from forms import WtCoGenForm
from controler.recursos import Recursos
from django.http.response import HttpResponse
from django.shortcuts import render, redirect
from controler.util import ler_urls_arquivo, get_tempo_execucao_formatado, \
    get_numero_formatado, upload_dados_acesso_twitter_arquivo, upload_arquivo_perplexidade, \
    upload_corpus_usuario
from controler.crawler_factory import CrawlerFactory


@login_required(login_url='/login/')
def index(request):
    crawler_factory = CrawlerFactory.get(request.user.email)
    if crawler_factory.processamento_em_execucao():
        return redirect('uCrawnler:processamento')

    context = {"corpus_gerado": CrawlerFacadeBase.corpus_compactado_gerado,
               "user": request.user}

    return render(request, "uCrawnler/index.html", context)


def get_dominios_selecionados(dominios):
    if "Todos" in dominios:
        dominios.remove("Todos")
        return dominios
    return dominios


@login_required(login_url='/login/')
def processamento(request):
    crawler_facade = CrawlerFactory.get(request.user.email).get_crawler_em_execucao()

    context = {"status_processamento": crawler_facade.status_processamento,
               "processamento_em_execucao": crawler_facade.processamento_em_execucao,
               "contagem_palavras": get_numero_formatado(str(crawler_facade.contagem_palavras)),
               "tempo_execucao": get_tempo_execucao_formatado(crawler_facade.tempo_processamento),
               "abrangencia": crawler_facade.abrangencia,
               "user": request.user}

    if crawler_facade.abrangencia == "twitter":
        context["contagem_twittes"] = get_numero_formatado(str(crawler_facade.contagem_twittes))
    elif crawler_facade.abrangencia == "web":
        context["contagem_paginas"] = get_numero_formatado(str(crawler_facade.contagem_paginas))
    else:
        context["contagem_paginas"] = 0
    return render(request, "uCrawnler/processamento.html", context)


@login_required(login_url='/login/')
def parar_processamento(request):
    crawler_facade = CrawlerFactory.get(request.user.email).get_crawler_em_execucao()
    crawler_facade.parar_crawler()
    return redirect("uCrawnler:processamento", permanent=True)


@login_required(login_url='/login/')
def download_corpora(request):
    nome_arquivo = Recursos(request.user.email).nome_completo_arquivo_compactado
    wrapper = FileWrapper(file(nome_arquivo))
    response = HttpResponse(wrapper, content_type='application/x-gzip')
    response['Content-Disposition'] = 'attachment; filename= %s' % os.path.basename(nome_arquivo)
    response['Content-Length'] = os.path.getsize(nome_arquivo)
    return response


def processe_se_abrangencia_twitter(request, crawler_factory, abrangencia, arquivo_conf_twitter, opcoes):

    if abrangencia != "twitter":
        return False, None

    crawler_facade = crawler_factory.get_twitter_crawler_facade()
    configuracoes = {}
    erros = {}
    try:
        configuracoes = upload_dados_acesso_twitter_arquivo(arquivo_conf_twitter, request.user.email)
        crawler_facade.validar_credenciais_twitter(configuracoes)
    except TweepError as e:
        erros = {"erros": ["Não foi possível se contectar ao twitter usando as credenciais informadas."]}
    except Exception as e:
        erros = {"erros":(str(e),)}

    if "erros" in erros:
        return True, render(request, "uCrawnler/index.html", erros)

    opcoes.update(configuracoes)
    crawler_facade.iniciar_twitter_crawler(opcoes)

    return True, redirect('uCrawnler:processamento', permanent=True)

def processe_se_abrangencia_web(form, cf, request):
    if form.abrangencia != "web":
        return False, None

    crawler_facade = cf.get_news_crawler_facade()

    dominios = []
    urls_usuario = []

    if form.opcao_coleta_selecionada == "palavras_chave":
        # É preciso que o usuário tenha informado pelo menos uma palavra chave
        if not form.palavras_chave:
            # Exibir mensagem de erro e mandar renderizar
            return render(request, 'uCrawnler/index.html', {"user": request.user})
        crawler_facade.iniciar_web_crawler_com_palavras_chave(**form.opcoes)
        return True, redirect('uCrawnler:processamento', permanent=True)

    if form.opcao_coleta_selecionada == "urls_sementes":
        # É preciso haver, nesse caso, pelo menos um domínio selecionado
        dominios = get_dominios_selecionados(form.slc_dominios)

    elif form.opcao_coleta_selecionada == "arquivo_urls":
        arquivo_urls = form.coleta_arquivo_file
        try:
            urls_usuario = ler_urls_arquivo(arquivo_urls, request.user.email)
        except Exception as e:
            return True, render(request, 'uCrawnler/index.html', {"user": request.user, "erros": (str(e),)})

    crawler_facade.iniciar_web_crawler_com_urls_sementes(urls_usuario= urls_usuario, dominios= dominios, **form.opcoes)

    return True, redirect('uCrawnler:processamento', permanent=True)

def processe_para_abrangencia_arquivo_proprio(form, cf, request):
    upload_corpus_usuario(form.arquivo_corpus_proprio, Recursos(request.user.email))
    sf = cf.get_single_file_processor()
    sf.iniciar_single_file_processor(form.opcoes)
    return redirect('uCrawnler:processamento', permanent=True)



@login_required(login_url='/login/')
def iniciar(request):
    cf = CrawlerFactory.get(request.user.email)
    if cf.processamento_em_execucao():
        return redirect("uCrawnler:processamento", permanent=True)

    if not request.method == "POST":
        return render(request, "uCrawnler/index.html", {"form": WtCoGenForm(), "user": request.user})
    else:
        form = WtCoGenForm(request)

    abrangencia_twitter, retorno_esperado_se_abrangencia_twitter = processe_se_abrangencia_twitter(request, cf, form.abrangencia,
                                                                                                   form.arquivo_conf_twitter,
                                                                                                  form.opcoes)
    if abrangencia_twitter:
        return retorno_esperado_se_abrangencia_twitter

    abrangencia_web, retorno_esperado_se_abrangencia_web = processe_se_abrangencia_web(form, cf, request)

    if form.calcular_perplexidade:
        upload_arquivo_perplexidade(form.arquivo_perplexidade, Recursos(request.user.email))

    if abrangencia_web:
        return retorno_esperado_se_abrangencia_web

    return processe_para_abrangencia_arquivo_proprio(form, cf, request)

uCrawnler/uCrawnler/templates/uCrawnler/editar_dados_usuario.html
{% extends "uCrawnler/template.html" %}

{% block title %}
Web Crawler - Processing
{% endblock %}

{% block content %}

<div class="row">
    <hr>
    <div class="col-md-3">
        <h1> Personal Info </h1>
    </div>
    <div class="col-md-6">
        <form action="{% url 'editar_dados_usuario' %}" method="post" class="form-horizontal" role="form">
            {% csrf_token %}

            <div class="form-group">
                <label class="col-md-2 control-label" for="nome">Name <label style='color:red;'>*</label>: </label>

                 <div class="col-md-10">
                    <input type="text" class="form-control" id="nome" name="nome" value="{{user.first_name}}" >
                 </div>
            </div>

            <div class="form-group">
                <label class="col-md-2 control-label" for="sobrenome">Last name <label style='color:red;'>*</label>: </label>
                <div class="col-md-10">
                    <input type="text" class="form-control" id="sobrenome" name="sobrenome" value="{{user.last_name}}">
                </div>
            </div>

            <div class="form-group">
                <label class="col-md-2 control-label" for="email">Email <label style='color:red;'>*</label>:</label>
                <div class="col-md-10">
                    <input type="email" class="form-control" id="email" name="email" value="{{user.email}}" readonly>
                </div>
            </div>

            <div class="form-group">
                <label class="col-md-2 control-label" for="senha"> Password <label style='color:red;'>*</label>: </label>
                <div class="col-md-10">
                    <input type="password" class="form-control" id="senha" name="senha">
                </div>
            </div>

            <div class="form-group">
                <label class="col-md-2 control-label" for="confirmacao_senha">Confirm password <label style='color:red;'>*</label>:</label>
                <div class="col-md-10">
                    <input type="password" class="form-control" id="confirmacao_senha" name="confirmacao_senha">
                </div>
            </div>

            {% if erro %}
                <p style="font-size:90%; color: red;"> {{erro}}</p>
            {%elif info %}
                <p style="font-size:90%;font-weight: bold;"> {{info}}</p>
            {% endif %}

             <div class="form-group">
                 <label class="col-md-3"></label>
                 <div class="col-md-8">
                    <input type="submit" class="btn btn-default" value="Save Changes"> </input>
                     <span></span>
                    <a href="{% url 'uCrawnler:index' %}" class="btn btn-default">
                        Return
                    </a>
                 </div>
            </div>
        </form>
    </div>
    <div class="col-md-3"></div>

    {% endblock %}

uCrawnler/uCrawnler/templates/uCrawnler/erro_alert.html
{% if erros %}
        <div class="alert alert-danger text-left fade in">
            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
            {% for erro in erros %}
                {{erro}}
                <br/>
            {% endfor %}
        </div>
{% endif %}

uCrawnler/uCrawnler/templates/uCrawnler/index.html
{% extends "uCrawnler/template.html" %}

{% block title %}
    uCrawnler
{% endblock %}

{% block content %}

{% include "uCrawnler/erro_alert.html" %}

<div class="container-fluid" style="width: 80%">
    <div class="row">
        <div class="col-md-12">
            {% include "uCrawnler/index/abas_navegacao.html" %}
        </div>
    </div>

    <form action="{% url 'uCrawnler:iniciar' %}"
          method="post"
          enctype="multipart/form-data"
          id="frmPrincipal">

            {% csrf_token %}
            <div class="tab-content">
                {% include "uCrawnler/index/aba_crawler.html"%}
                {% include "uCrawnler/index/aba_modelo_linguagem.html"%}
                {% include "uCrawnler/index/aba_entidades_nomeadas.html"%}
                {% include "uCrawnler/index/aba_limpeza_corpus.html"%}
                {% include "uCrawnler/index/aba_geracao.html"%}
            </div>
    </form>
</div>

{% endblock %}

uCrawnler/uCrawnler/templates/uCrawnler/login.html
<!DOCTYPE html>
<html >
<head>
    <meta charset="UTF-8">
    <title>Login</title>

    <link rel='stylesheet prefetch' href='http://netdna.bootstrapcdn.com/bootstrap/3.0.2/css/bootstrap.min.css'>
    <link rel="stylesheet" href="/static/css/style_login.css">
</head>

<body>

<div class="wrapper">
    <form class="form-signin" method="post" action="{% url 'login' %}">
        {% csrf_token %}
        <h2 class="form-signin-heading">Login</h2>
        <input type="text" class="form-control" id="email"
               maxlength="254" name="email" placeholder="Email" required=""
               autofocus="true" />
        <input type="password" class="form-control" id="senha"
               name="senha"
               placeholder="Password" required=""/>
        {% if erro %}
            <p style="font-size:90%; color: red;"> {{erro}}</p>
        {%elif info %}
            <p style="font-size:90%;font-weight: bold;"> {{info}}</p>
        {% endif %}

        <input type='hidden' name='next' value='{{next}}' />
        <button class="btn btn-lg btn-primary btn-block" type="submit">Login</button>
        <br/>
        <div style="text-align: center;">
            <a href="{% url 'novo_usuario' %}">Register</a>
        </div>
    </form>
</div>
</body>
</html>

uCrawnler/uCrawnler/templates/uCrawnler/novo_usuario.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <!--<link rel="shortcut icon" href="/favicon.ico" type="image/x-icon">-->
    <title>Web Crawler</title>
    <link rel='stylesheet prefetch' href='http://netdna.bootstrapcdn.com/bootstrap/3.0.2/css/bootstrap.min.css'>
</head>
<body>
<div class="container" style="margin-top: 40px">
    <div class="row">
        <h1> Cadastrar novo usuário</h1>
        <div class="col-md-6">
            <div class="panel panel-info">
                <div class="panel-heading">Enter your details</div>
                <div class="panel-body">
                    <form action="{% url 'cadastrar_novo_usuario' %}" method="post">
                        {% csrf_token %}
                        <div class="form-group">
                            <label class="control-label" for="nome">Name</label>
                            <label style="color:red;">*</label>
                            <input type="text" class="form-control" id="nome" name="nome" >
                        </div>
                        <div class="form-group">
                            <label class="control-label" for="sobrenome">Surname</label>
                            <label style="color:red;">*</label>
                            <input type="text" class="form-control" id="sobrenome" name="sobrenome" >
                        </div>
                        <div class="form-group">
                            <label class="control-label" for="email">Email</label>
                            <label style="color:red;">*</label>
                            <input type="email" class="form-control" id="email" name="email">
                        </div>

                        <div class="form-group">
                            <label class="control-label" for="senha">Password</label>
                            <label style="color:red;">*</label>
                            <input type="password" class="form-control" id="senha" name="senha">
                        </div>
                        <div class="form-group">
                            <label class="control-label" for="confirmacao_senha">Confirm your password</label>
                            <label style="color:red;">*</label>
                            <input type="password" class="form-control" id="confirmacao_senha" name="confirmacao_senha">
                        </div>
                        {% if erro %}
                        <p style="font-size:90%; color: red;"> {{erro}}</p>
                        {%elif info %}
                        <p style="font-size:90%;"> {{info}}</p>
                        {% endif %}
                        <button type="submit" class="btn btn-default">Register</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
</body>
</html>

uCrawnler/uCrawnler/templates/uCrawnler/processamento.html
{% extends "uCrawnler/template.html" %}


{% block title %}
    Web Crawler - Processamento
{% endblock %}

{% block content %}
<form action="{% url 'uCrawnler:processamento' %}" method="post">
    {%if processamento_em_execucao %}
        <script>
            setTimeout(function() {window.location=window.location;}, 1000);
        </script>
    {% endif %}

    <div class="panel panel-primary" style="margin-left:10px;margin-right:10px">
        <div class="panel-heading" style="text-align: center;">
            <h3 class="panel-title">Processing info</h3>
        </div>
        <div class="panel-body">
             <table class="table table-bordered table-condensed" style="margin=">
                <tr style="font-weight:bold;text-align: center;">
                    <td>
                       Status
                    </td>
                    <td>
                       Words
                    </td>
                    <td>
                        {% if abrangencia == "web" %}
                            Pages
                        {% else %}
                            Twittes
                        {% endif %}
                    </td>
                    <td>
                        Execution time
                    </td>
                    <td>
                        Action
                    </td>
                </tr>
                <tr style="text-align: center">
                    <td>
                        {% if processamento_em_execucao %}
                            {{status_processamento}} <i class="fa fa-spinner fa-spin"></i>
                        {% elif status_processamento == "Done" %}
                            Finished <i class="fa fa-check"></i>
                        {% else %}
                            Stoped <i class="fa fa-meh-o"></i>
                        {% endif %}
                    </td>
                     <td>
                         {%if status_processamento != "Parado" %}
                            {{contagem_palavras}}
                        {% else %}
                            --
                        {% endif %}
                    </td>

                     <td>
                        {% if status_processamento != "Parado" and  abrangencia == "web"%}
                            {{contagem_paginas}}
                        {% elif status_processamento != "Parado" and  abrangencia == "twitter" %}
                            {{contagem_twittes}}
                         {% else %}
                            --
                        {% endif %}
                    </td>

                    <td>
                        {%if status_processamento != "Parado" %}
                            {{tempo_execucao}}
                        {% else %}
                            --
                        {% endif %}
                    </td>
                    <td >
                         {%if status_processamento == "Downloading corpus" %}
                            <div class="span8">
                                <a href="{% url 'uCrawnler:parar_processamento' %}"> <i class="fa fa-stop" style="color:black" title="Stop"></i></a>
                            </div>
                        {% elif status_processamento == "Done" %}
                            <div class="span8">
                                 <a href="{% url 'uCrawnler:download_corpora' %}"> <i class="fa fa-download" style="color:black"  title="Download"></i></a>
                            </div>
                        {% elif  status_processamento == "Processing corpus"%}
                            Please, wait a minute...
                        {% else %}
                            --
                        {% endif %}
                    </td>
                </tr>
            </table>

             {%if status_processamento != "Finalizado" and status_processamento != "Parado" %}
                When the current processing end, you can make a new search.
             {%endif %}

        </div>

    </div>
</form>
{% endblock %}

uCrawnler/uCrawnler/templates/uCrawnler/template.html
<!DOCTYPE html>
{% load i18n %}
<html>
<head lang="pt-br">
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>

    <link href="/static/bower_components/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="/static/bower_components/metisMenu/dist/metisMenu.min.css" rel="stylesheet">
    <link href="/static/css/timeline.css" rel="stylesheet">
    <link href="/static/css/sb-admin-2.css" rel="stylesheet">
    <link href="/static/bower_components/morrisjs/morris.css" rel="stylesheet">
    <link href="/static/bower_components/font-awesome/css/font-awesome.min.css" rel="stylesheet">
    <link href="/static/css/estilo.css" rel="stylesheet"/>
    <link href="/static/lou-multi-select/css/multi-select.css" media="screen" rel="stylesheet" type="text/css">

    <script src="/static/bower_components/jquery/dist/jquery.js"></script>
    <script src="/static/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="/static/bower_components/metisMenu/dist/metisMenu.min.js"></script>
    <script src="/static/script/sb-admin-2.js"></script>
    <script src="/static/script/script.js"></script>
    <script src="/static/script/bootstrap-filestyle.js"></script>

</head>
<body>
<div class="container-fluid content">
    <div class="row">
        <div class="col-lg-12">
            <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                    </button>
                    <a class="navbar-brand" href="{% url 'uCrawnler:index' %}"><p><img height="40px" src="/static/imagem/ufs_logo.png"/> uCrawnler </p></a>
                </div>

                <!-- Ícones da barra superior-->
                <ul class="nav navbar-top-links navbar-right">
                    <li>
                        <a href="{% url 'uCrawnler:index' %}">
                            <i class="fa fa-home fa-fw"></i><label style="font-size: 11pt; padding-left: 2px;">
                                "Home"
                        </label>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <i class="fa fa-users fa-fw"></i><label style="font-size: 11pt; padding-left: 2px;"> About us</label>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <i class="fa fa-info fa-fw"></i><label style="font-size: 11pt; padding-left: 2px;"> Documentation</label>
                        </a>
                    </li>
                    {% if corpus_gerado %}
                    <li>
                        <a href="{% url 'uCrawnler:processamento' %}">
                            <i class="fa fa-thumbs-o-up" title="Corpora disponível para download"></i><label style="font-size: 11pt; padding-left: 2px;"> Corpora </label>
                        </a>
                    </li>
                    {% endif %}
                    <li>
                        <a  href="{% url 'editar_dados_usuario' %}">
                            <i class="fa fa-user" title="Editar meus dados"></i><label style="font-size: 11pt; padding-left: 2px;"> Personal info </label>
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'logout' %}">
                            ({{user.first_name}})
                            <i class="fa fa-sign-out" ></i><label style="font-size: 11pt; padding-left: 2px;" > Log out </label>
                        </a>
                    </li>

                </ul>
            </nav>
            {% block content %}
            {% endblock %}
        </div>
    </div>
</div>


<script>$(document).ready(function() {
                $(":file").filestyle('buttonText', 'Select file');
                $(":file").filestyle({disabled: true});
            });</script>
<script>
        $("#radio_urls_sementes").click(function(){
            $(":file").filestyle('disabled', true);
            tratarFonteColetaUrlsSementes();
        });
        $("#radio_coleta_arquivo").click(function(){
            $("#coleta_select_file").filestyle('disabled', false);
            desabilitaLabel();
        });
        $("#radio_abrangencia_twitter").click(function(){
            $("#arquivo_dados_acesso_twitter").filestyle('disabled', false);
            desabilitaLabel();
        });
        $("#radio_palavras_chave").click(function(){
            $(":file").filestyle('disabled', true);
            desabilitaLabel();
        });
        $(".dominio_checkboxes").click(function(){
            var someonechecked = 0;
            for(var i = 0; i < document.getElementsByClassName("dominio_checkboxes").length; i++){
            if (document.getElementsByClassName("dominio_checkboxes")[i].checked == true){
                someonechecked = 1;
                break;
            }
            }
            if (someonechecked === 0)
                habilitaLabel();
            else
                desabilitaLabel();
        });
    </script>
</body>
</html>